// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/note.proto

package grpc_note

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteRequest) Reset() {
	*x = NoteRequest{}
	mi := &file_proto_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteRequest) ProtoMessage() {}

func (x *NoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteRequest.ProtoReflect.Descriptor instead.
func (*NoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_proto_rawDescGZIP(), []int{0}
}

func (x *NoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AlterNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterNoteRequest) Reset() {
	*x = AlterNoteRequest{}
	mi := &file_proto_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterNoteRequest) ProtoMessage() {}

func (x *AlterNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterNoteRequest.ProtoReflect.Descriptor instead.
func (*AlterNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_proto_rawDescGZIP(), []int{1}
}

func (x *AlterNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlterNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlterNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type NoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResponse) Reset() {
	*x = NoteResponse{}
	mi := &file_proto_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResponse) ProtoMessage() {}

func (x *NoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResponse.ProtoReflect.Descriptor instead.
func (*NoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_note_proto_rawDescGZIP(), []int{2}
}

func (x *NoteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AlterNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterNoteResponse) Reset() {
	*x = AlterNoteResponse{}
	mi := &file_proto_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterNoteResponse) ProtoMessage() {}

func (x *AlterNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterNoteResponse.ProtoReflect.Descriptor instead.
func (*AlterNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_note_proto_rawDescGZIP(), []int{3}
}

func (x *AlterNoteResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AlterNoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_note_proto protoreflect.FileDescriptor

const file_proto_note_proto_rawDesc = "" +
	"\n" +
	"\x10proto/note.proto\x12\x04note\"=\n" +
	"\vNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"R\n" +
	"\x10AlterNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"N\n" +
	"\fNoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"N\n" +
	"\x11AlterNoteResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf8\x01\n" +
	"\x04Note\x125\n" +
	"\n" +
	"CreateNote\x12\x11.note.NoteRequest\x1a\x12.note.NoteResponse\"\x00\x127\n" +
	"\aGetNote\x12\x16.note.AlterNoteRequest\x1a\x12.note.NoteResponse\"\x00\x12?\n" +
	"\n" +
	"UpdateNote\x12\x16.note.AlterNoteRequest\x1a\x17.note.AlterNoteResponse\"\x00\x12?\n" +
	"\n" +
	"DeleteNote\x12\x16.note.AlterNoteRequest\x1a\x17.note.AlterNoteResponse\"\x00B%Z#github.com/CrimsonKarma44/grpc_noteb\x06proto3"

var (
	file_proto_note_proto_rawDescOnce sync.Once
	file_proto_note_proto_rawDescData []byte
)

func file_proto_note_proto_rawDescGZIP() []byte {
	file_proto_note_proto_rawDescOnce.Do(func() {
		file_proto_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_note_proto_rawDesc), len(file_proto_note_proto_rawDesc)))
	})
	return file_proto_note_proto_rawDescData
}

var file_proto_note_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_note_proto_goTypes = []any{
	(*NoteRequest)(nil),       // 0: note.NoteRequest
	(*AlterNoteRequest)(nil),  // 1: note.AlterNoteRequest
	(*NoteResponse)(nil),      // 2: note.NoteResponse
	(*AlterNoteResponse)(nil), // 3: note.AlterNoteResponse
}
var file_proto_note_proto_depIdxs = []int32{
	0, // 0: note.Note.CreateNote:input_type -> note.NoteRequest
	1, // 1: note.Note.GetNote:input_type -> note.AlterNoteRequest
	1, // 2: note.Note.UpdateNote:input_type -> note.AlterNoteRequest
	1, // 3: note.Note.DeleteNote:input_type -> note.AlterNoteRequest
	2, // 4: note.Note.CreateNote:output_type -> note.NoteResponse
	2, // 5: note.Note.GetNote:output_type -> note.NoteResponse
	3, // 6: note.Note.UpdateNote:output_type -> note.AlterNoteResponse
	3, // 7: note.Note.DeleteNote:output_type -> note.AlterNoteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_note_proto_init() }
func file_proto_note_proto_init() {
	if File_proto_note_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_note_proto_rawDesc), len(file_proto_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_note_proto_goTypes,
		DependencyIndexes: file_proto_note_proto_depIdxs,
		MessageInfos:      file_proto_note_proto_msgTypes,
	}.Build()
	File_proto_note_proto = out.File
	file_proto_note_proto_goTypes = nil
	file_proto_note_proto_depIdxs = nil
}
