// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package Blogging_Platform_API

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Blog struct {
	ID        int64
	Title     string
	Content   sql.NullString
	Category  sql.NullString
	Tags      json.RawMessage
	Createdat sql.NullTime
	Updatedat time.Time
}
