// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package Blogging_Platform_API

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createBlog = `-- name: CreateBlog :execresult
INSERT INTO blog (title, content, category, tags, createdAt, updatedAt)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateBlogParams struct {
	Title     string
	Content   sql.NullString
	Category  sql.NullString
	Tags      json.RawMessage
	Createdat sql.NullTime
	Updatedat time.Time
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBlog,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Tags,
		arg.Createdat,
		arg.Updatedat,
	)
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE
FROM blog
WHERE id = ?
`

func (q *Queries) DeleteBlog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlog, id)
	return err
}
